mariadb:
  image: mariadb:10.1.11
  ports:
    - "3306"
  volumes:
    - ./volumes/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./volumes/mariadb/conf.d:/etc/mysql/conf.d
  environment:
    - MYSQL_ROOT_PASSWORD=password
  hostname:
    db.mso.testlab.openecomp.org
    
mso:
  image: openecomp/mso
  ports:
    - "3904:3904"
    - "3905:3905"    
    - "8080:8080"
    - "9990:9990"    
  volumes:
    - ./volumes/mso/chef-config:/shared
  links:
    - mariadb:mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=password
  hostname:
    mso.mso.testlab.openecomp.org