server:
    port: 8082
    tomcat:
        max-threads: 50
ssl-enable: false
mso:
  logPath: logs
  site-name: onapheat
  catalog:
    db:
      spring:
        endpoint: http://c1.vm1.mso.simpledemo.openecomp.org:8082
  db:
    auth: Basic YnBlbDpwYXNzd29yZDEk
spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/catalogdb
    username: cataloguser
    password: catalog123
    driver-class-name: org.mariadb.jdbc.Driver
    initialize: false
    initialization-mode: never
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      enable-lazy-load-no-trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    usercredentials:
    -
      username: bpel
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: BPEL-Client
    -  
      username: mso_admin
      password: '$2b$10$byoF5q.VngZd8nj63q2Rm.bbAGUQrNG3DliPtc5l9nJIbXpXyCfrG'
      role: ACTUATOR

#Actuator
management: 
  context-path: /manage

flyway:
  baseline-on-migrate: true
  url: jdbc:mariadb://mariadb:3306/catalogdb
  user: cataloguser
  password: catalog123
