server:
    port: 9092
    tomcat:
        max-threads: 4
    ssl:
      key-alias: so@so.onap.org
      key--store-password: 'ywsqCy:EEo#j}HJHM7z^Rk[L'
      key-store: classpath:so-vnfm-adapter.p12
      key-store-type: PKCS12

ssl-enable: false

aai:
  auth: 2A11B07DB6214A839394AA1EC5844695F5114FC407FF5422625FB00175A3DCB8A1FF745F22867EFA72D5369D599BBD88DA8BED4233CF5586
  version: v15
  endpoint: https://aai.onap:8443

mso:
  key: 07a7159d3bf51a0e53be7a8f89699be7
  site-name: localSite
  logPath: ./logs/vnfm-adapter
  config:
    cadi: {{ include "cadi.keys" . | nindent 8}}
  msb-ip: msb-iag.{{ include "common.namespace" . }}
  msb-port: 80

sdc:
  username: mso
  password: 76966BDD3C7414A03F7037264FF2E6C8EEC6C28F2B67F2840A1ED857C0260FEE731D73F47F828E5527125D29FD25D3E0DE39EE44C058906BF1657DE77BF897EECA93BDC07FA64F
  key: 566B754875657232314F5548556D3665
  endpoint: http://sdc-simulator:9991/

vnfmadapter:
  endpoint: http://vnfm-adapter:9092

etsi-catalog-manager:
  vnfpkgm:
    endpoint: https://msb-iag.{{ include "common.namespace" . }}:443/api/vnfpkgm/v1
    http:
      client:
        ssl:
          trust-store: ${TRUSTSTORE}
          trust-store-password: ${TRUSTSTORE_PASSWORD}

spring:
  security:
    usercredentials:
      - username: test
        password: '$2a$12$Zi3AuYcZoZO/gBQyUtST2.F5N6HqcTtaNci2Et.ufsQhski56srIu'
        role: BPEL-Client
      - username: vnfm
        password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
        role: BPEL-Client
